/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OpfsProofRouteImport } from './routes/opfs-proof'
import { Route as OpfsConnectionsProofRouteImport } from './routes/opfs-connections-proof'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as ApiWaitlistRouteImport } from './routes/api/waitlist'
import { Route as ApiSnippetsRouteImport } from './routes/api/snippets'
import { Route as ApiSignaturesRouteImport } from './routes/api/signatures'
import { Route as ApiSendRouteImport } from './routes/api/send'
import { Route as ApiPullRequestsRouteImport } from './routes/api/pull-requests'
import { Route as ApiMessageRouteImport } from './routes/api/message'
import { Route as ApiLabelsRouteImport } from './routes/api/labels'
import { Route as ApiImageProxyRouteImport } from './routes/api/image-proxy'
import { Route as ApiGmailSignatureRouteImport } from './routes/api/gmail-signature'
import { Route as ApiGithubIssuesRouteImport } from './routes/api/github-issues'
import { Route as ApiEmailsRouteImport } from './routes/api/emails'
import { Route as ApiDraftRouteImport } from './routes/api/draft'
import { Route as ApiContactsRouteImport } from './routes/api/contacts'
import { Route as ApiAgentExecuteRouteImport } from './routes/api/agent-execute'
import { Route as ApiAccountsRouteImport } from './routes/api/accounts'
import { Route as AppWebhooksRouteImport } from './routes/_app/webhooks'
import { Route as AppTrashRouteImport } from './routes/_app/trash'
import { Route as AppSpamRouteImport } from './routes/_app/spam'
import { Route as AppSentRouteImport } from './routes/_app/sent'
import { Route as AppPullRequestsRouteImport } from './routes/_app/pull-requests'
import { Route as AppLabeledRouteImport } from './routes/_app/labeled'
import { Route as AppIssuesRouteImport } from './routes/_app/issues'
import { Route as AppDraftsRouteImport } from './routes/_app/drafts'
import { Route as AppArchivedRouteImport } from './routes/_app/archived'
import { Route as AppApiRouteImport } from './routes/_app/api'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppEmailIdRouteImport } from './routes/_app/email.$id'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OpfsProofRoute = OpfsProofRouteImport.update({
  id: '/opfs-proof',
  path: '/opfs-proof',
  getParentRoute: () => rootRouteImport,
} as any)
const OpfsConnectionsProofRoute = OpfsConnectionsProofRouteImport.update({
  id: '/opfs-connections-proof',
  path: '/opfs-connections-proof',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ApiWaitlistRoute = ApiWaitlistRouteImport.update({
  id: '/api/waitlist',
  path: '/api/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSnippetsRoute = ApiSnippetsRouteImport.update({
  id: '/api/snippets',
  path: '/api/snippets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSignaturesRoute = ApiSignaturesRouteImport.update({
  id: '/api/signatures',
  path: '/api/signatures',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendRoute = ApiSendRouteImport.update({
  id: '/api/send',
  path: '/api/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPullRequestsRoute = ApiPullRequestsRouteImport.update({
  id: '/api/pull-requests',
  path: '/api/pull-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMessageRoute = ApiMessageRouteImport.update({
  id: '/api/message',
  path: '/api/message',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLabelsRoute = ApiLabelsRouteImport.update({
  id: '/api/labels',
  path: '/api/labels',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImageProxyRoute = ApiImageProxyRouteImport.update({
  id: '/api/image-proxy',
  path: '/api/image-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGmailSignatureRoute = ApiGmailSignatureRouteImport.update({
  id: '/api/gmail-signature',
  path: '/api/gmail-signature',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubIssuesRoute = ApiGithubIssuesRouteImport.update({
  id: '/api/github-issues',
  path: '/api/github-issues',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmailsRoute = ApiEmailsRouteImport.update({
  id: '/api/emails',
  path: '/api/emails',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDraftRoute = ApiDraftRouteImport.update({
  id: '/api/draft',
  path: '/api/draft',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactsRoute = ApiContactsRouteImport.update({
  id: '/api/contacts',
  path: '/api/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentExecuteRoute = ApiAgentExecuteRouteImport.update({
  id: '/api/agent-execute',
  path: '/api/agent-execute',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountsRoute = ApiAccountsRouteImport.update({
  id: '/api/accounts',
  path: '/api/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWebhooksRoute = AppWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => AppRoute,
} as any)
const AppTrashRoute = AppTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => AppRoute,
} as any)
const AppSpamRoute = AppSpamRouteImport.update({
  id: '/spam',
  path: '/spam',
  getParentRoute: () => AppRoute,
} as any)
const AppSentRoute = AppSentRouteImport.update({
  id: '/sent',
  path: '/sent',
  getParentRoute: () => AppRoute,
} as any)
const AppPullRequestsRoute = AppPullRequestsRouteImport.update({
  id: '/pull-requests',
  path: '/pull-requests',
  getParentRoute: () => AppRoute,
} as any)
const AppLabeledRoute = AppLabeledRouteImport.update({
  id: '/labeled',
  path: '/labeled',
  getParentRoute: () => AppRoute,
} as any)
const AppIssuesRoute = AppIssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => AppRoute,
} as any)
const AppDraftsRoute = AppDraftsRouteImport.update({
  id: '/drafts',
  path: '/drafts',
  getParentRoute: () => AppRoute,
} as any)
const AppArchivedRoute = AppArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => AppRoute,
} as any)
const AppApiRoute = AppApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppEmailIdRoute = AppEmailIdRouteImport.update({
  id: '/email/$id',
  path: '/email/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/opfs-connections-proof': typeof OpfsConnectionsProofRoute
  '/opfs-proof': typeof OpfsProofRoute
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof SignInRoute
  '/api': typeof AppApiRoute
  '/archived': typeof AppArchivedRoute
  '/drafts': typeof AppDraftsRoute
  '/issues': typeof AppIssuesRoute
  '/labeled': typeof AppLabeledRoute
  '/pull-requests': typeof AppPullRequestsRoute
  '/sent': typeof AppSentRoute
  '/spam': typeof AppSpamRoute
  '/trash': typeof AppTrashRoute
  '/webhooks': typeof AppWebhooksRoute
  '/api/accounts': typeof ApiAccountsRoute
  '/api/agent-execute': typeof ApiAgentExecuteRoute
  '/api/contacts': typeof ApiContactsRoute
  '/api/draft': typeof ApiDraftRoute
  '/api/emails': typeof ApiEmailsRoute
  '/api/github-issues': typeof ApiGithubIssuesRoute
  '/api/gmail-signature': typeof ApiGmailSignatureRoute
  '/api/image-proxy': typeof ApiImageProxyRoute
  '/api/labels': typeof ApiLabelsRoute
  '/api/message': typeof ApiMessageRoute
  '/api/pull-requests': typeof ApiPullRequestsRoute
  '/api/send': typeof ApiSendRoute
  '/api/signatures': typeof ApiSignaturesRoute
  '/api/snippets': typeof ApiSnippetsRoute
  '/api/waitlist': typeof ApiWaitlistRoute
  '/email/$id': typeof AppEmailIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/opfs-connections-proof': typeof OpfsConnectionsProofRoute
  '/opfs-proof': typeof OpfsProofRoute
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof SignInRoute
  '/api': typeof AppApiRoute
  '/archived': typeof AppArchivedRoute
  '/drafts': typeof AppDraftsRoute
  '/issues': typeof AppIssuesRoute
  '/labeled': typeof AppLabeledRoute
  '/pull-requests': typeof AppPullRequestsRoute
  '/sent': typeof AppSentRoute
  '/spam': typeof AppSpamRoute
  '/trash': typeof AppTrashRoute
  '/webhooks': typeof AppWebhooksRoute
  '/api/accounts': typeof ApiAccountsRoute
  '/api/agent-execute': typeof ApiAgentExecuteRoute
  '/api/contacts': typeof ApiContactsRoute
  '/api/draft': typeof ApiDraftRoute
  '/api/emails': typeof ApiEmailsRoute
  '/api/github-issues': typeof ApiGithubIssuesRoute
  '/api/gmail-signature': typeof ApiGmailSignatureRoute
  '/api/image-proxy': typeof ApiImageProxyRoute
  '/api/labels': typeof ApiLabelsRoute
  '/api/message': typeof ApiMessageRoute
  '/api/pull-requests': typeof ApiPullRequestsRoute
  '/api/send': typeof ApiSendRoute
  '/api/signatures': typeof ApiSignaturesRoute
  '/api/snippets': typeof ApiSnippetsRoute
  '/api/waitlist': typeof ApiWaitlistRoute
  '/': typeof AppIndexRoute
  '/email/$id': typeof AppEmailIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/opfs-connections-proof': typeof OpfsConnectionsProofRoute
  '/opfs-proof': typeof OpfsProofRoute
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof SignInRoute
  '/_app/api': typeof AppApiRoute
  '/_app/archived': typeof AppArchivedRoute
  '/_app/drafts': typeof AppDraftsRoute
  '/_app/issues': typeof AppIssuesRoute
  '/_app/labeled': typeof AppLabeledRoute
  '/_app/pull-requests': typeof AppPullRequestsRoute
  '/_app/sent': typeof AppSentRoute
  '/_app/spam': typeof AppSpamRoute
  '/_app/trash': typeof AppTrashRoute
  '/_app/webhooks': typeof AppWebhooksRoute
  '/api/accounts': typeof ApiAccountsRoute
  '/api/agent-execute': typeof ApiAgentExecuteRoute
  '/api/contacts': typeof ApiContactsRoute
  '/api/draft': typeof ApiDraftRoute
  '/api/emails': typeof ApiEmailsRoute
  '/api/github-issues': typeof ApiGithubIssuesRoute
  '/api/gmail-signature': typeof ApiGmailSignatureRoute
  '/api/image-proxy': typeof ApiImageProxyRoute
  '/api/labels': typeof ApiLabelsRoute
  '/api/message': typeof ApiMessageRoute
  '/api/pull-requests': typeof ApiPullRequestsRoute
  '/api/send': typeof ApiSendRoute
  '/api/signatures': typeof ApiSignaturesRoute
  '/api/snippets': typeof ApiSnippetsRoute
  '/api/waitlist': typeof ApiWaitlistRoute
  '/_app/': typeof AppIndexRoute
  '/_app/email/$id': typeof AppEmailIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/opfs-connections-proof'
    | '/opfs-proof'
    | '/privacy'
    | '/sign-in'
    | '/api'
    | '/archived'
    | '/drafts'
    | '/issues'
    | '/labeled'
    | '/pull-requests'
    | '/sent'
    | '/spam'
    | '/trash'
    | '/webhooks'
    | '/api/accounts'
    | '/api/agent-execute'
    | '/api/contacts'
    | '/api/draft'
    | '/api/emails'
    | '/api/github-issues'
    | '/api/gmail-signature'
    | '/api/image-proxy'
    | '/api/labels'
    | '/api/message'
    | '/api/pull-requests'
    | '/api/send'
    | '/api/signatures'
    | '/api/snippets'
    | '/api/waitlist'
    | '/email/$id'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/opfs-connections-proof'
    | '/opfs-proof'
    | '/privacy'
    | '/sign-in'
    | '/api'
    | '/archived'
    | '/drafts'
    | '/issues'
    | '/labeled'
    | '/pull-requests'
    | '/sent'
    | '/spam'
    | '/trash'
    | '/webhooks'
    | '/api/accounts'
    | '/api/agent-execute'
    | '/api/contacts'
    | '/api/draft'
    | '/api/emails'
    | '/api/github-issues'
    | '/api/gmail-signature'
    | '/api/image-proxy'
    | '/api/labels'
    | '/api/message'
    | '/api/pull-requests'
    | '/api/send'
    | '/api/signatures'
    | '/api/snippets'
    | '/api/waitlist'
    | '/'
    | '/email/$id'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_app'
    | '/opfs-connections-proof'
    | '/opfs-proof'
    | '/privacy'
    | '/sign-in'
    | '/_app/api'
    | '/_app/archived'
    | '/_app/drafts'
    | '/_app/issues'
    | '/_app/labeled'
    | '/_app/pull-requests'
    | '/_app/sent'
    | '/_app/spam'
    | '/_app/trash'
    | '/_app/webhooks'
    | '/api/accounts'
    | '/api/agent-execute'
    | '/api/contacts'
    | '/api/draft'
    | '/api/emails'
    | '/api/github-issues'
    | '/api/gmail-signature'
    | '/api/image-proxy'
    | '/api/labels'
    | '/api/message'
    | '/api/pull-requests'
    | '/api/send'
    | '/api/signatures'
    | '/api/snippets'
    | '/api/waitlist'
    | '/_app/'
    | '/_app/email/$id'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  OpfsConnectionsProofRoute: typeof OpfsConnectionsProofRoute
  OpfsProofRoute: typeof OpfsProofRoute
  PrivacyRoute: typeof PrivacyRoute
  SignInRoute: typeof SignInRoute
  ApiAccountsRoute: typeof ApiAccountsRoute
  ApiAgentExecuteRoute: typeof ApiAgentExecuteRoute
  ApiContactsRoute: typeof ApiContactsRoute
  ApiDraftRoute: typeof ApiDraftRoute
  ApiEmailsRoute: typeof ApiEmailsRoute
  ApiGithubIssuesRoute: typeof ApiGithubIssuesRoute
  ApiGmailSignatureRoute: typeof ApiGmailSignatureRoute
  ApiImageProxyRoute: typeof ApiImageProxyRoute
  ApiLabelsRoute: typeof ApiLabelsRoute
  ApiMessageRoute: typeof ApiMessageRoute
  ApiPullRequestsRoute: typeof ApiPullRequestsRoute
  ApiSendRoute: typeof ApiSendRoute
  ApiSignaturesRoute: typeof ApiSignaturesRoute
  ApiSnippetsRoute: typeof ApiSnippetsRoute
  ApiWaitlistRoute: typeof ApiWaitlistRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opfs-proof': {
      id: '/opfs-proof'
      path: '/opfs-proof'
      fullPath: '/opfs-proof'
      preLoaderRoute: typeof OpfsProofRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opfs-connections-proof': {
      id: '/opfs-connections-proof'
      path: '/opfs-connections-proof'
      fullPath: '/opfs-connections-proof'
      preLoaderRoute: typeof OpfsConnectionsProofRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/waitlist': {
      id: '/api/waitlist'
      path: '/api/waitlist'
      fullPath: '/api/waitlist'
      preLoaderRoute: typeof ApiWaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/snippets': {
      id: '/api/snippets'
      path: '/api/snippets'
      fullPath: '/api/snippets'
      preLoaderRoute: typeof ApiSnippetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/signatures': {
      id: '/api/signatures'
      path: '/api/signatures'
      fullPath: '/api/signatures'
      preLoaderRoute: typeof ApiSignaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send': {
      id: '/api/send'
      path: '/api/send'
      fullPath: '/api/send'
      preLoaderRoute: typeof ApiSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pull-requests': {
      id: '/api/pull-requests'
      path: '/api/pull-requests'
      fullPath: '/api/pull-requests'
      preLoaderRoute: typeof ApiPullRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/message': {
      id: '/api/message'
      path: '/api/message'
      fullPath: '/api/message'
      preLoaderRoute: typeof ApiMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/labels': {
      id: '/api/labels'
      path: '/api/labels'
      fullPath: '/api/labels'
      preLoaderRoute: typeof ApiLabelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/image-proxy': {
      id: '/api/image-proxy'
      path: '/api/image-proxy'
      fullPath: '/api/image-proxy'
      preLoaderRoute: typeof ApiImageProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gmail-signature': {
      id: '/api/gmail-signature'
      path: '/api/gmail-signature'
      fullPath: '/api/gmail-signature'
      preLoaderRoute: typeof ApiGmailSignatureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github-issues': {
      id: '/api/github-issues'
      path: '/api/github-issues'
      fullPath: '/api/github-issues'
      preLoaderRoute: typeof ApiGithubIssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/emails': {
      id: '/api/emails'
      path: '/api/emails'
      fullPath: '/api/emails'
      preLoaderRoute: typeof ApiEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/draft': {
      id: '/api/draft'
      path: '/api/draft'
      fullPath: '/api/draft'
      preLoaderRoute: typeof ApiDraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contacts': {
      id: '/api/contacts'
      path: '/api/contacts'
      fullPath: '/api/contacts'
      preLoaderRoute: typeof ApiContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent-execute': {
      id: '/api/agent-execute'
      path: '/api/agent-execute'
      fullPath: '/api/agent-execute'
      preLoaderRoute: typeof ApiAgentExecuteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/accounts': {
      id: '/api/accounts'
      path: '/api/accounts'
      fullPath: '/api/accounts'
      preLoaderRoute: typeof ApiAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/webhooks': {
      id: '/_app/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof AppWebhooksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trash': {
      id: '/_app/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof AppTrashRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/spam': {
      id: '/_app/spam'
      path: '/spam'
      fullPath: '/spam'
      preLoaderRoute: typeof AppSpamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sent': {
      id: '/_app/sent'
      path: '/sent'
      fullPath: '/sent'
      preLoaderRoute: typeof AppSentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pull-requests': {
      id: '/_app/pull-requests'
      path: '/pull-requests'
      fullPath: '/pull-requests'
      preLoaderRoute: typeof AppPullRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/labeled': {
      id: '/_app/labeled'
      path: '/labeled'
      fullPath: '/labeled'
      preLoaderRoute: typeof AppLabeledRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/issues': {
      id: '/_app/issues'
      path: '/issues'
      fullPath: '/issues'
      preLoaderRoute: typeof AppIssuesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/drafts': {
      id: '/_app/drafts'
      path: '/drafts'
      fullPath: '/drafts'
      preLoaderRoute: typeof AppDraftsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/archived': {
      id: '/_app/archived'
      path: '/archived'
      fullPath: '/archived'
      preLoaderRoute: typeof AppArchivedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/api': {
      id: '/_app/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof AppApiRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/email/$id': {
      id: '/_app/email/$id'
      path: '/email/$id'
      fullPath: '/email/$id'
      preLoaderRoute: typeof AppEmailIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppApiRoute: typeof AppApiRoute
  AppArchivedRoute: typeof AppArchivedRoute
  AppDraftsRoute: typeof AppDraftsRoute
  AppIssuesRoute: typeof AppIssuesRoute
  AppLabeledRoute: typeof AppLabeledRoute
  AppPullRequestsRoute: typeof AppPullRequestsRoute
  AppSentRoute: typeof AppSentRoute
  AppSpamRoute: typeof AppSpamRoute
  AppTrashRoute: typeof AppTrashRoute
  AppWebhooksRoute: typeof AppWebhooksRoute
  AppIndexRoute: typeof AppIndexRoute
  AppEmailIdRoute: typeof AppEmailIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApiRoute: AppApiRoute,
  AppArchivedRoute: AppArchivedRoute,
  AppDraftsRoute: AppDraftsRoute,
  AppIssuesRoute: AppIssuesRoute,
  AppLabeledRoute: AppLabeledRoute,
  AppPullRequestsRoute: AppPullRequestsRoute,
  AppSentRoute: AppSentRoute,
  AppSpamRoute: AppSpamRoute,
  AppTrashRoute: AppTrashRoute,
  AppWebhooksRoute: AppWebhooksRoute,
  AppIndexRoute: AppIndexRoute,
  AppEmailIdRoute: AppEmailIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  OpfsConnectionsProofRoute: OpfsConnectionsProofRoute,
  OpfsProofRoute: OpfsProofRoute,
  PrivacyRoute: PrivacyRoute,
  SignInRoute: SignInRoute,
  ApiAccountsRoute: ApiAccountsRoute,
  ApiAgentExecuteRoute: ApiAgentExecuteRoute,
  ApiContactsRoute: ApiContactsRoute,
  ApiDraftRoute: ApiDraftRoute,
  ApiEmailsRoute: ApiEmailsRoute,
  ApiGithubIssuesRoute: ApiGithubIssuesRoute,
  ApiGmailSignatureRoute: ApiGmailSignatureRoute,
  ApiImageProxyRoute: ApiImageProxyRoute,
  ApiLabelsRoute: ApiLabelsRoute,
  ApiMessageRoute: ApiMessageRoute,
  ApiPullRequestsRoute: ApiPullRequestsRoute,
  ApiSendRoute: ApiSendRoute,
  ApiSignaturesRoute: ApiSignaturesRoute,
  ApiSnippetsRoute: ApiSnippetsRoute,
  ApiWaitlistRoute: ApiWaitlistRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
