/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OpfsProofRouteImport } from './routes/opfs-proof'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as ApiWaitlistRouteImport } from './routes/api/waitlist'
import { Route as ApiSnippetsRouteImport } from './routes/api/snippets'
import { Route as ApiSignaturesRouteImport } from './routes/api/signatures'
import { Route as ApiSendRouteImport } from './routes/api/send'
import { Route as ApiPullRequestsRouteImport } from './routes/api/pull-requests'
import { Route as ApiMessageRouteImport } from './routes/api/message'
import { Route as ApiLabelsRouteImport } from './routes/api/labels'
import { Route as ApiImageProxyRouteImport } from './routes/api/image-proxy'
import { Route as ApiGmailSignatureRouteImport } from './routes/api/gmail-signature'
import { Route as ApiGithubIssuesRouteImport } from './routes/api/github-issues'
import { Route as ApiEmailsRouteImport } from './routes/api/emails'
import { Route as ApiDraftRouteImport } from './routes/api/draft'
import { Route as ApiContactsRouteImport } from './routes/api/contacts'
import { Route as ApiAgentExecuteRouteImport } from './routes/api/agent-execute'
import { Route as ApiAccountsRouteImport } from './routes/api/accounts'
import { Route as AppTrashRouteImport } from './routes/_app/trash'
import { Route as AppTrainingRouteImport } from './routes/_app/training'
import { Route as AppSpamRouteImport } from './routes/_app/spam'
import { Route as AppSkillsRouteImport } from './routes/_app/skills'
import { Route as AppSentRouteImport } from './routes/_app/sent'
import { Route as AppRuntimeRouteImport } from './routes/_app/runtime'
import { Route as AppLabeledRouteImport } from './routes/_app/labeled'
import { Route as AppEvalsRouteImport } from './routes/_app/evals'
import { Route as AppDraftsRouteImport } from './routes/_app/drafts'
import { Route as AppDatasetsRouteImport } from './routes/_app/datasets'
import { Route as AppArtifactsRouteImport } from './routes/_app/artifacts'
import { Route as AppArchivedRouteImport } from './routes/_app/archived'
import { Route as AppAgentsRouteImport } from './routes/_app/agents'
import { Route as AppSourcesIndexRouteImport } from './routes/_app/sources/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppEmailIdRouteImport } from './routes/_app/email.$id'
import { Route as AppSourcesGmailIndexRouteImport } from './routes/_app/sources/gmail/index'
import { Route as AppSourcesGmailTrashRouteImport } from './routes/_app/sources/gmail/trash'
import { Route as AppSourcesGmailSpamRouteImport } from './routes/_app/sources/gmail/spam'
import { Route as AppSourcesGmailSentRouteImport } from './routes/_app/sources/gmail/sent'
import { Route as AppSourcesGmailLabeledRouteImport } from './routes/_app/sources/gmail/labeled'
import { Route as AppSourcesGmailHubRouteImport } from './routes/_app/sources/gmail/hub'
import { Route as AppSourcesGmailDraftsRouteImport } from './routes/_app/sources/gmail/drafts'
import { Route as AppSourcesGmailArchivedRouteImport } from './routes/_app/sources/gmail/archived'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OpfsProofRoute = OpfsProofRouteImport.update({
  id: '/opfs-proof',
  path: '/opfs-proof',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ApiWaitlistRoute = ApiWaitlistRouteImport.update({
  id: '/api/waitlist',
  path: '/api/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSnippetsRoute = ApiSnippetsRouteImport.update({
  id: '/api/snippets',
  path: '/api/snippets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSignaturesRoute = ApiSignaturesRouteImport.update({
  id: '/api/signatures',
  path: '/api/signatures',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendRoute = ApiSendRouteImport.update({
  id: '/api/send',
  path: '/api/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPullRequestsRoute = ApiPullRequestsRouteImport.update({
  id: '/api/pull-requests',
  path: '/api/pull-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMessageRoute = ApiMessageRouteImport.update({
  id: '/api/message',
  path: '/api/message',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLabelsRoute = ApiLabelsRouteImport.update({
  id: '/api/labels',
  path: '/api/labels',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImageProxyRoute = ApiImageProxyRouteImport.update({
  id: '/api/image-proxy',
  path: '/api/image-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGmailSignatureRoute = ApiGmailSignatureRouteImport.update({
  id: '/api/gmail-signature',
  path: '/api/gmail-signature',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubIssuesRoute = ApiGithubIssuesRouteImport.update({
  id: '/api/github-issues',
  path: '/api/github-issues',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmailsRoute = ApiEmailsRouteImport.update({
  id: '/api/emails',
  path: '/api/emails',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDraftRoute = ApiDraftRouteImport.update({
  id: '/api/draft',
  path: '/api/draft',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactsRoute = ApiContactsRouteImport.update({
  id: '/api/contacts',
  path: '/api/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentExecuteRoute = ApiAgentExecuteRouteImport.update({
  id: '/api/agent-execute',
  path: '/api/agent-execute',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountsRoute = ApiAccountsRouteImport.update({
  id: '/api/accounts',
  path: '/api/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTrashRoute = AppTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => AppRoute,
} as any)
const AppTrainingRoute = AppTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => AppRoute,
} as any)
const AppSpamRoute = AppSpamRouteImport.update({
  id: '/spam',
  path: '/spam',
  getParentRoute: () => AppRoute,
} as any)
const AppSkillsRoute = AppSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AppRoute,
} as any)
const AppSentRoute = AppSentRouteImport.update({
  id: '/sent',
  path: '/sent',
  getParentRoute: () => AppRoute,
} as any)
const AppRuntimeRoute = AppRuntimeRouteImport.update({
  id: '/runtime',
  path: '/runtime',
  getParentRoute: () => AppRoute,
} as any)
const AppLabeledRoute = AppLabeledRouteImport.update({
  id: '/labeled',
  path: '/labeled',
  getParentRoute: () => AppRoute,
} as any)
const AppEvalsRoute = AppEvalsRouteImport.update({
  id: '/evals',
  path: '/evals',
  getParentRoute: () => AppRoute,
} as any)
const AppDraftsRoute = AppDraftsRouteImport.update({
  id: '/drafts',
  path: '/drafts',
  getParentRoute: () => AppRoute,
} as any)
const AppDatasetsRoute = AppDatasetsRouteImport.update({
  id: '/datasets',
  path: '/datasets',
  getParentRoute: () => AppRoute,
} as any)
const AppArtifactsRoute = AppArtifactsRouteImport.update({
  id: '/artifacts',
  path: '/artifacts',
  getParentRoute: () => AppRoute,
} as any)
const AppArchivedRoute = AppArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsRoute = AppAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AppRoute,
} as any)
const AppSourcesIndexRoute = AppSourcesIndexRouteImport.update({
  id: '/sources/',
  path: '/sources/',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppEmailIdRoute = AppEmailIdRouteImport.update({
  id: '/email/$id',
  path: '/email/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSourcesGmailIndexRoute = AppSourcesGmailIndexRouteImport.update({
  id: '/sources/gmail/',
  path: '/sources/gmail/',
  getParentRoute: () => AppRoute,
} as any)
const AppSourcesGmailTrashRoute = AppSourcesGmailTrashRouteImport.update({
  id: '/sources/gmail/trash',
  path: '/sources/gmail/trash',
  getParentRoute: () => AppRoute,
} as any)
const AppSourcesGmailSpamRoute = AppSourcesGmailSpamRouteImport.update({
  id: '/sources/gmail/spam',
  path: '/sources/gmail/spam',
  getParentRoute: () => AppRoute,
} as any)
const AppSourcesGmailSentRoute = AppSourcesGmailSentRouteImport.update({
  id: '/sources/gmail/sent',
  path: '/sources/gmail/sent',
  getParentRoute: () => AppRoute,
} as any)
const AppSourcesGmailLabeledRoute = AppSourcesGmailLabeledRouteImport.update({
  id: '/sources/gmail/labeled',
  path: '/sources/gmail/labeled',
  getParentRoute: () => AppRoute,
} as any)
const AppSourcesGmailHubRoute = AppSourcesGmailHubRouteImport.update({
  id: '/sources/gmail/hub',
  path: '/sources/gmail/hub',
  getParentRoute: () => AppRoute,
} as any)
const AppSourcesGmailDraftsRoute = AppSourcesGmailDraftsRouteImport.update({
  id: '/sources/gmail/drafts',
  path: '/sources/gmail/drafts',
  getParentRoute: () => AppRoute,
} as any)
const AppSourcesGmailArchivedRoute = AppSourcesGmailArchivedRouteImport.update({
  id: '/sources/gmail/archived',
  path: '/sources/gmail/archived',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/opfs-proof': typeof OpfsProofRoute
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof SignInRoute
  '/agents': typeof AppAgentsRoute
  '/archived': typeof AppArchivedRoute
  '/artifacts': typeof AppArtifactsRoute
  '/datasets': typeof AppDatasetsRoute
  '/drafts': typeof AppDraftsRoute
  '/evals': typeof AppEvalsRoute
  '/labeled': typeof AppLabeledRoute
  '/runtime': typeof AppRuntimeRoute
  '/sent': typeof AppSentRoute
  '/skills': typeof AppSkillsRoute
  '/spam': typeof AppSpamRoute
  '/training': typeof AppTrainingRoute
  '/trash': typeof AppTrashRoute
  '/api/accounts': typeof ApiAccountsRoute
  '/api/agent-execute': typeof ApiAgentExecuteRoute
  '/api/contacts': typeof ApiContactsRoute
  '/api/draft': typeof ApiDraftRoute
  '/api/emails': typeof ApiEmailsRoute
  '/api/github-issues': typeof ApiGithubIssuesRoute
  '/api/gmail-signature': typeof ApiGmailSignatureRoute
  '/api/image-proxy': typeof ApiImageProxyRoute
  '/api/labels': typeof ApiLabelsRoute
  '/api/message': typeof ApiMessageRoute
  '/api/pull-requests': typeof ApiPullRequestsRoute
  '/api/send': typeof ApiSendRoute
  '/api/signatures': typeof ApiSignaturesRoute
  '/api/snippets': typeof ApiSnippetsRoute
  '/api/waitlist': typeof ApiWaitlistRoute
  '/email/$id': typeof AppEmailIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/sources/': typeof AppSourcesIndexRoute
  '/sources/gmail/archived': typeof AppSourcesGmailArchivedRoute
  '/sources/gmail/drafts': typeof AppSourcesGmailDraftsRoute
  '/sources/gmail/hub': typeof AppSourcesGmailHubRoute
  '/sources/gmail/labeled': typeof AppSourcesGmailLabeledRoute
  '/sources/gmail/sent': typeof AppSourcesGmailSentRoute
  '/sources/gmail/spam': typeof AppSourcesGmailSpamRoute
  '/sources/gmail/trash': typeof AppSourcesGmailTrashRoute
  '/sources/gmail/': typeof AppSourcesGmailIndexRoute
}
export interface FileRoutesByTo {
  '/opfs-proof': typeof OpfsProofRoute
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof SignInRoute
  '/agents': typeof AppAgentsRoute
  '/archived': typeof AppArchivedRoute
  '/artifacts': typeof AppArtifactsRoute
  '/datasets': typeof AppDatasetsRoute
  '/drafts': typeof AppDraftsRoute
  '/evals': typeof AppEvalsRoute
  '/labeled': typeof AppLabeledRoute
  '/runtime': typeof AppRuntimeRoute
  '/sent': typeof AppSentRoute
  '/skills': typeof AppSkillsRoute
  '/spam': typeof AppSpamRoute
  '/training': typeof AppTrainingRoute
  '/trash': typeof AppTrashRoute
  '/api/accounts': typeof ApiAccountsRoute
  '/api/agent-execute': typeof ApiAgentExecuteRoute
  '/api/contacts': typeof ApiContactsRoute
  '/api/draft': typeof ApiDraftRoute
  '/api/emails': typeof ApiEmailsRoute
  '/api/github-issues': typeof ApiGithubIssuesRoute
  '/api/gmail-signature': typeof ApiGmailSignatureRoute
  '/api/image-proxy': typeof ApiImageProxyRoute
  '/api/labels': typeof ApiLabelsRoute
  '/api/message': typeof ApiMessageRoute
  '/api/pull-requests': typeof ApiPullRequestsRoute
  '/api/send': typeof ApiSendRoute
  '/api/signatures': typeof ApiSignaturesRoute
  '/api/snippets': typeof ApiSnippetsRoute
  '/api/waitlist': typeof ApiWaitlistRoute
  '/': typeof AppIndexRoute
  '/email/$id': typeof AppEmailIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/sources': typeof AppSourcesIndexRoute
  '/sources/gmail/archived': typeof AppSourcesGmailArchivedRoute
  '/sources/gmail/drafts': typeof AppSourcesGmailDraftsRoute
  '/sources/gmail/hub': typeof AppSourcesGmailHubRoute
  '/sources/gmail/labeled': typeof AppSourcesGmailLabeledRoute
  '/sources/gmail/sent': typeof AppSourcesGmailSentRoute
  '/sources/gmail/spam': typeof AppSourcesGmailSpamRoute
  '/sources/gmail/trash': typeof AppSourcesGmailTrashRoute
  '/sources/gmail': typeof AppSourcesGmailIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/opfs-proof': typeof OpfsProofRoute
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof SignInRoute
  '/_app/agents': typeof AppAgentsRoute
  '/_app/archived': typeof AppArchivedRoute
  '/_app/artifacts': typeof AppArtifactsRoute
  '/_app/datasets': typeof AppDatasetsRoute
  '/_app/drafts': typeof AppDraftsRoute
  '/_app/evals': typeof AppEvalsRoute
  '/_app/labeled': typeof AppLabeledRoute
  '/_app/runtime': typeof AppRuntimeRoute
  '/_app/sent': typeof AppSentRoute
  '/_app/skills': typeof AppSkillsRoute
  '/_app/spam': typeof AppSpamRoute
  '/_app/training': typeof AppTrainingRoute
  '/_app/trash': typeof AppTrashRoute
  '/api/accounts': typeof ApiAccountsRoute
  '/api/agent-execute': typeof ApiAgentExecuteRoute
  '/api/contacts': typeof ApiContactsRoute
  '/api/draft': typeof ApiDraftRoute
  '/api/emails': typeof ApiEmailsRoute
  '/api/github-issues': typeof ApiGithubIssuesRoute
  '/api/gmail-signature': typeof ApiGmailSignatureRoute
  '/api/image-proxy': typeof ApiImageProxyRoute
  '/api/labels': typeof ApiLabelsRoute
  '/api/message': typeof ApiMessageRoute
  '/api/pull-requests': typeof ApiPullRequestsRoute
  '/api/send': typeof ApiSendRoute
  '/api/signatures': typeof ApiSignaturesRoute
  '/api/snippets': typeof ApiSnippetsRoute
  '/api/waitlist': typeof ApiWaitlistRoute
  '/_app/': typeof AppIndexRoute
  '/_app/email/$id': typeof AppEmailIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/sources/': typeof AppSourcesIndexRoute
  '/_app/sources/gmail/archived': typeof AppSourcesGmailArchivedRoute
  '/_app/sources/gmail/drafts': typeof AppSourcesGmailDraftsRoute
  '/_app/sources/gmail/hub': typeof AppSourcesGmailHubRoute
  '/_app/sources/gmail/labeled': typeof AppSourcesGmailLabeledRoute
  '/_app/sources/gmail/sent': typeof AppSourcesGmailSentRoute
  '/_app/sources/gmail/spam': typeof AppSourcesGmailSpamRoute
  '/_app/sources/gmail/trash': typeof AppSourcesGmailTrashRoute
  '/_app/sources/gmail/': typeof AppSourcesGmailIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/opfs-proof'
    | '/privacy'
    | '/sign-in'
    | '/agents'
    | '/archived'
    | '/artifacts'
    | '/datasets'
    | '/drafts'
    | '/evals'
    | '/labeled'
    | '/runtime'
    | '/sent'
    | '/skills'
    | '/spam'
    | '/training'
    | '/trash'
    | '/api/accounts'
    | '/api/agent-execute'
    | '/api/contacts'
    | '/api/draft'
    | '/api/emails'
    | '/api/github-issues'
    | '/api/gmail-signature'
    | '/api/image-proxy'
    | '/api/labels'
    | '/api/message'
    | '/api/pull-requests'
    | '/api/send'
    | '/api/signatures'
    | '/api/snippets'
    | '/api/waitlist'
    | '/email/$id'
    | '/api/auth/$'
    | '/sources/'
    | '/sources/gmail/archived'
    | '/sources/gmail/drafts'
    | '/sources/gmail/hub'
    | '/sources/gmail/labeled'
    | '/sources/gmail/sent'
    | '/sources/gmail/spam'
    | '/sources/gmail/trash'
    | '/sources/gmail/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/opfs-proof'
    | '/privacy'
    | '/sign-in'
    | '/agents'
    | '/archived'
    | '/artifacts'
    | '/datasets'
    | '/drafts'
    | '/evals'
    | '/labeled'
    | '/runtime'
    | '/sent'
    | '/skills'
    | '/spam'
    | '/training'
    | '/trash'
    | '/api/accounts'
    | '/api/agent-execute'
    | '/api/contacts'
    | '/api/draft'
    | '/api/emails'
    | '/api/github-issues'
    | '/api/gmail-signature'
    | '/api/image-proxy'
    | '/api/labels'
    | '/api/message'
    | '/api/pull-requests'
    | '/api/send'
    | '/api/signatures'
    | '/api/snippets'
    | '/api/waitlist'
    | '/'
    | '/email/$id'
    | '/api/auth/$'
    | '/sources'
    | '/sources/gmail/archived'
    | '/sources/gmail/drafts'
    | '/sources/gmail/hub'
    | '/sources/gmail/labeled'
    | '/sources/gmail/sent'
    | '/sources/gmail/spam'
    | '/sources/gmail/trash'
    | '/sources/gmail'
  id:
    | '__root__'
    | '/_app'
    | '/opfs-proof'
    | '/privacy'
    | '/sign-in'
    | '/_app/agents'
    | '/_app/archived'
    | '/_app/artifacts'
    | '/_app/datasets'
    | '/_app/drafts'
    | '/_app/evals'
    | '/_app/labeled'
    | '/_app/runtime'
    | '/_app/sent'
    | '/_app/skills'
    | '/_app/spam'
    | '/_app/training'
    | '/_app/trash'
    | '/api/accounts'
    | '/api/agent-execute'
    | '/api/contacts'
    | '/api/draft'
    | '/api/emails'
    | '/api/github-issues'
    | '/api/gmail-signature'
    | '/api/image-proxy'
    | '/api/labels'
    | '/api/message'
    | '/api/pull-requests'
    | '/api/send'
    | '/api/signatures'
    | '/api/snippets'
    | '/api/waitlist'
    | '/_app/'
    | '/_app/email/$id'
    | '/api/auth/$'
    | '/_app/sources/'
    | '/_app/sources/gmail/archived'
    | '/_app/sources/gmail/drafts'
    | '/_app/sources/gmail/hub'
    | '/_app/sources/gmail/labeled'
    | '/_app/sources/gmail/sent'
    | '/_app/sources/gmail/spam'
    | '/_app/sources/gmail/trash'
    | '/_app/sources/gmail/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  OpfsProofRoute: typeof OpfsProofRoute
  PrivacyRoute: typeof PrivacyRoute
  SignInRoute: typeof SignInRoute
  ApiAccountsRoute: typeof ApiAccountsRoute
  ApiAgentExecuteRoute: typeof ApiAgentExecuteRoute
  ApiContactsRoute: typeof ApiContactsRoute
  ApiDraftRoute: typeof ApiDraftRoute
  ApiEmailsRoute: typeof ApiEmailsRoute
  ApiGithubIssuesRoute: typeof ApiGithubIssuesRoute
  ApiGmailSignatureRoute: typeof ApiGmailSignatureRoute
  ApiImageProxyRoute: typeof ApiImageProxyRoute
  ApiLabelsRoute: typeof ApiLabelsRoute
  ApiMessageRoute: typeof ApiMessageRoute
  ApiPullRequestsRoute: typeof ApiPullRequestsRoute
  ApiSendRoute: typeof ApiSendRoute
  ApiSignaturesRoute: typeof ApiSignaturesRoute
  ApiSnippetsRoute: typeof ApiSnippetsRoute
  ApiWaitlistRoute: typeof ApiWaitlistRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opfs-proof': {
      id: '/opfs-proof'
      path: '/opfs-proof'
      fullPath: '/opfs-proof'
      preLoaderRoute: typeof OpfsProofRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/waitlist': {
      id: '/api/waitlist'
      path: '/api/waitlist'
      fullPath: '/api/waitlist'
      preLoaderRoute: typeof ApiWaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/snippets': {
      id: '/api/snippets'
      path: '/api/snippets'
      fullPath: '/api/snippets'
      preLoaderRoute: typeof ApiSnippetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/signatures': {
      id: '/api/signatures'
      path: '/api/signatures'
      fullPath: '/api/signatures'
      preLoaderRoute: typeof ApiSignaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send': {
      id: '/api/send'
      path: '/api/send'
      fullPath: '/api/send'
      preLoaderRoute: typeof ApiSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pull-requests': {
      id: '/api/pull-requests'
      path: '/api/pull-requests'
      fullPath: '/api/pull-requests'
      preLoaderRoute: typeof ApiPullRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/message': {
      id: '/api/message'
      path: '/api/message'
      fullPath: '/api/message'
      preLoaderRoute: typeof ApiMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/labels': {
      id: '/api/labels'
      path: '/api/labels'
      fullPath: '/api/labels'
      preLoaderRoute: typeof ApiLabelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/image-proxy': {
      id: '/api/image-proxy'
      path: '/api/image-proxy'
      fullPath: '/api/image-proxy'
      preLoaderRoute: typeof ApiImageProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gmail-signature': {
      id: '/api/gmail-signature'
      path: '/api/gmail-signature'
      fullPath: '/api/gmail-signature'
      preLoaderRoute: typeof ApiGmailSignatureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github-issues': {
      id: '/api/github-issues'
      path: '/api/github-issues'
      fullPath: '/api/github-issues'
      preLoaderRoute: typeof ApiGithubIssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/emails': {
      id: '/api/emails'
      path: '/api/emails'
      fullPath: '/api/emails'
      preLoaderRoute: typeof ApiEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/draft': {
      id: '/api/draft'
      path: '/api/draft'
      fullPath: '/api/draft'
      preLoaderRoute: typeof ApiDraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contacts': {
      id: '/api/contacts'
      path: '/api/contacts'
      fullPath: '/api/contacts'
      preLoaderRoute: typeof ApiContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent-execute': {
      id: '/api/agent-execute'
      path: '/api/agent-execute'
      fullPath: '/api/agent-execute'
      preLoaderRoute: typeof ApiAgentExecuteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/accounts': {
      id: '/api/accounts'
      path: '/api/accounts'
      fullPath: '/api/accounts'
      preLoaderRoute: typeof ApiAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/trash': {
      id: '/_app/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof AppTrashRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/training': {
      id: '/_app/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof AppTrainingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/spam': {
      id: '/_app/spam'
      path: '/spam'
      fullPath: '/spam'
      preLoaderRoute: typeof AppSpamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/skills': {
      id: '/_app/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof AppSkillsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sent': {
      id: '/_app/sent'
      path: '/sent'
      fullPath: '/sent'
      preLoaderRoute: typeof AppSentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/runtime': {
      id: '/_app/runtime'
      path: '/runtime'
      fullPath: '/runtime'
      preLoaderRoute: typeof AppRuntimeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/labeled': {
      id: '/_app/labeled'
      path: '/labeled'
      fullPath: '/labeled'
      preLoaderRoute: typeof AppLabeledRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/evals': {
      id: '/_app/evals'
      path: '/evals'
      fullPath: '/evals'
      preLoaderRoute: typeof AppEvalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/drafts': {
      id: '/_app/drafts'
      path: '/drafts'
      fullPath: '/drafts'
      preLoaderRoute: typeof AppDraftsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/datasets': {
      id: '/_app/datasets'
      path: '/datasets'
      fullPath: '/datasets'
      preLoaderRoute: typeof AppDatasetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/artifacts': {
      id: '/_app/artifacts'
      path: '/artifacts'
      fullPath: '/artifacts'
      preLoaderRoute: typeof AppArtifactsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/archived': {
      id: '/_app/archived'
      path: '/archived'
      fullPath: '/archived'
      preLoaderRoute: typeof AppArchivedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents': {
      id: '/_app/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AppAgentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sources/': {
      id: '/_app/sources/'
      path: '/sources'
      fullPath: '/sources/'
      preLoaderRoute: typeof AppSourcesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/email/$id': {
      id: '/_app/email/$id'
      path: '/email/$id'
      fullPath: '/email/$id'
      preLoaderRoute: typeof AppEmailIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sources/gmail/': {
      id: '/_app/sources/gmail/'
      path: '/sources/gmail'
      fullPath: '/sources/gmail/'
      preLoaderRoute: typeof AppSourcesGmailIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sources/gmail/trash': {
      id: '/_app/sources/gmail/trash'
      path: '/sources/gmail/trash'
      fullPath: '/sources/gmail/trash'
      preLoaderRoute: typeof AppSourcesGmailTrashRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sources/gmail/spam': {
      id: '/_app/sources/gmail/spam'
      path: '/sources/gmail/spam'
      fullPath: '/sources/gmail/spam'
      preLoaderRoute: typeof AppSourcesGmailSpamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sources/gmail/sent': {
      id: '/_app/sources/gmail/sent'
      path: '/sources/gmail/sent'
      fullPath: '/sources/gmail/sent'
      preLoaderRoute: typeof AppSourcesGmailSentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sources/gmail/labeled': {
      id: '/_app/sources/gmail/labeled'
      path: '/sources/gmail/labeled'
      fullPath: '/sources/gmail/labeled'
      preLoaderRoute: typeof AppSourcesGmailLabeledRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sources/gmail/hub': {
      id: '/_app/sources/gmail/hub'
      path: '/sources/gmail/hub'
      fullPath: '/sources/gmail/hub'
      preLoaderRoute: typeof AppSourcesGmailHubRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sources/gmail/drafts': {
      id: '/_app/sources/gmail/drafts'
      path: '/sources/gmail/drafts'
      fullPath: '/sources/gmail/drafts'
      preLoaderRoute: typeof AppSourcesGmailDraftsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sources/gmail/archived': {
      id: '/_app/sources/gmail/archived'
      path: '/sources/gmail/archived'
      fullPath: '/sources/gmail/archived'
      preLoaderRoute: typeof AppSourcesGmailArchivedRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAgentsRoute: typeof AppAgentsRoute
  AppArchivedRoute: typeof AppArchivedRoute
  AppArtifactsRoute: typeof AppArtifactsRoute
  AppDatasetsRoute: typeof AppDatasetsRoute
  AppDraftsRoute: typeof AppDraftsRoute
  AppEvalsRoute: typeof AppEvalsRoute
  AppLabeledRoute: typeof AppLabeledRoute
  AppRuntimeRoute: typeof AppRuntimeRoute
  AppSentRoute: typeof AppSentRoute
  AppSkillsRoute: typeof AppSkillsRoute
  AppSpamRoute: typeof AppSpamRoute
  AppTrainingRoute: typeof AppTrainingRoute
  AppTrashRoute: typeof AppTrashRoute
  AppIndexRoute: typeof AppIndexRoute
  AppEmailIdRoute: typeof AppEmailIdRoute
  AppSourcesIndexRoute: typeof AppSourcesIndexRoute
  AppSourcesGmailArchivedRoute: typeof AppSourcesGmailArchivedRoute
  AppSourcesGmailDraftsRoute: typeof AppSourcesGmailDraftsRoute
  AppSourcesGmailHubRoute: typeof AppSourcesGmailHubRoute
  AppSourcesGmailLabeledRoute: typeof AppSourcesGmailLabeledRoute
  AppSourcesGmailSentRoute: typeof AppSourcesGmailSentRoute
  AppSourcesGmailSpamRoute: typeof AppSourcesGmailSpamRoute
  AppSourcesGmailTrashRoute: typeof AppSourcesGmailTrashRoute
  AppSourcesGmailIndexRoute: typeof AppSourcesGmailIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgentsRoute: AppAgentsRoute,
  AppArchivedRoute: AppArchivedRoute,
  AppArtifactsRoute: AppArtifactsRoute,
  AppDatasetsRoute: AppDatasetsRoute,
  AppDraftsRoute: AppDraftsRoute,
  AppEvalsRoute: AppEvalsRoute,
  AppLabeledRoute: AppLabeledRoute,
  AppRuntimeRoute: AppRuntimeRoute,
  AppSentRoute: AppSentRoute,
  AppSkillsRoute: AppSkillsRoute,
  AppSpamRoute: AppSpamRoute,
  AppTrainingRoute: AppTrainingRoute,
  AppTrashRoute: AppTrashRoute,
  AppIndexRoute: AppIndexRoute,
  AppEmailIdRoute: AppEmailIdRoute,
  AppSourcesIndexRoute: AppSourcesIndexRoute,
  AppSourcesGmailArchivedRoute: AppSourcesGmailArchivedRoute,
  AppSourcesGmailDraftsRoute: AppSourcesGmailDraftsRoute,
  AppSourcesGmailHubRoute: AppSourcesGmailHubRoute,
  AppSourcesGmailLabeledRoute: AppSourcesGmailLabeledRoute,
  AppSourcesGmailSentRoute: AppSourcesGmailSentRoute,
  AppSourcesGmailSpamRoute: AppSourcesGmailSpamRoute,
  AppSourcesGmailTrashRoute: AppSourcesGmailTrashRoute,
  AppSourcesGmailIndexRoute: AppSourcesGmailIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  OpfsProofRoute: OpfsProofRoute,
  PrivacyRoute: PrivacyRoute,
  SignInRoute: SignInRoute,
  ApiAccountsRoute: ApiAccountsRoute,
  ApiAgentExecuteRoute: ApiAgentExecuteRoute,
  ApiContactsRoute: ApiContactsRoute,
  ApiDraftRoute: ApiDraftRoute,
  ApiEmailsRoute: ApiEmailsRoute,
  ApiGithubIssuesRoute: ApiGithubIssuesRoute,
  ApiGmailSignatureRoute: ApiGmailSignatureRoute,
  ApiImageProxyRoute: ApiImageProxyRoute,
  ApiLabelsRoute: ApiLabelsRoute,
  ApiMessageRoute: ApiMessageRoute,
  ApiPullRequestsRoute: ApiPullRequestsRoute,
  ApiSendRoute: ApiSendRoute,
  ApiSignaturesRoute: ApiSignaturesRoute,
  ApiSnippetsRoute: ApiSnippetsRoute,
  ApiWaitlistRoute: ApiWaitlistRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
