/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSendRouteImport } from './routes/api/send'
import { Route as ApiMessageRouteImport } from './routes/api/message'
import { Route as ApiEmailsRouteImport } from './routes/api/emails'
import { Route as ApiAccountsRouteImport } from './routes/api/accounts'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendRoute = ApiSendRouteImport.update({
  id: '/api/send',
  path: '/api/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMessageRoute = ApiMessageRouteImport.update({
  id: '/api/message',
  path: '/api/message',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmailsRoute = ApiEmailsRouteImport.update({
  id: '/api/emails',
  path: '/api/emails',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountsRoute = ApiAccountsRouteImport.update({
  id: '/api/accounts',
  path: '/api/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/accounts': typeof ApiAccountsRoute
  '/api/emails': typeof ApiEmailsRoute
  '/api/message': typeof ApiMessageRoute
  '/api/send': typeof ApiSendRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/accounts': typeof ApiAccountsRoute
  '/api/emails': typeof ApiEmailsRoute
  '/api/message': typeof ApiMessageRoute
  '/api/send': typeof ApiSendRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/accounts': typeof ApiAccountsRoute
  '/api/emails': typeof ApiEmailsRoute
  '/api/message': typeof ApiMessageRoute
  '/api/send': typeof ApiSendRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/accounts'
    | '/api/emails'
    | '/api/message'
    | '/api/send'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/accounts'
    | '/api/emails'
    | '/api/message'
    | '/api/send'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/api/accounts'
    | '/api/emails'
    | '/api/message'
    | '/api/send'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAccountsRoute: typeof ApiAccountsRoute
  ApiEmailsRoute: typeof ApiEmailsRoute
  ApiMessageRoute: typeof ApiMessageRoute
  ApiSendRoute: typeof ApiSendRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send': {
      id: '/api/send'
      path: '/api/send'
      fullPath: '/api/send'
      preLoaderRoute: typeof ApiSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/message': {
      id: '/api/message'
      path: '/api/message'
      fullPath: '/api/message'
      preLoaderRoute: typeof ApiMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/emails': {
      id: '/api/emails'
      path: '/api/emails'
      fullPath: '/api/emails'
      preLoaderRoute: typeof ApiEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/accounts': {
      id: '/api/accounts'
      path: '/api/accounts'
      fullPath: '/api/accounts'
      preLoaderRoute: typeof ApiAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAccountsRoute: ApiAccountsRoute,
  ApiEmailsRoute: ApiEmailsRoute,
  ApiMessageRoute: ApiMessageRoute,
  ApiSendRoute: ApiSendRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
